### ISSUE TITLE
AuthN: Allow Stacked AuthN

### ISSUE THREAD

**Issue by ashcrow** [projectatomic/commissaire-http#33]
As a user of commissaire
I would like to be able to use more than one authn plugin
so that if one plugin works successfully the user is authn'd

This will help with #31 and #21 usage.

cc @gbraad

**Comment by gbraad** [comment]
+1
For now I would consider this a low-prio, but it does mean a wrapper for Keystone is not needed.

**Comment by gbraad** [comment]
Also like the user story approach. I would suggest this as much as possible going forward. Can aid in writing/considering automated test cases, focused on behavior

**Comment by ashcrow** [comment]
I think I'll end up having this done tomorrow morning. We'll see :smile:.

**Comment by gbraad** [comment]
Added reference for documentation purposes.
