### ISSUE TITLE
Pass-through REST API for Tang

### ISSUE THREAD

**Issue by mbarnes** [projectatomic/commissaire-http#59]
One integration point for Commissaire and Tang is to provide a simple pass-through REST API to the Tang server's REST API.

Proposed endpoints (based on Tang's [README](https://github.com/latchset/tang/blob/master/README.md)) include:
```
   GET  /api/v0/tang/adv         Fetch public keys
   GET  /api/v0/tang/adv/{kid}   Fetch public keys using specified signing key
   POST /api/v0/tang/rec/{kid}   Perform recovery using specified exchange key
```

The location of the Tang server would be specified in `commissaire.conf`, perhaps like:
```
   {
      "tang": { "server_url": "http://tang.server:port" }
   }
```

Another possible feature is an endpoint to perform key rotation on the Tang server by way of Ansible.  (For LUKS decryption via Tang, this would presumably be followed by a rolling reboot of relevant clusters.)

**Comment by ashcrow** [comment]
I like the endpoints but I think they should be versioned with the api (EX: ``v0``). These should work assuming ``clevis`` and any other tools needed can define the endpoint (which I would assume they can).

Unrelated but good to keep in mind, the ``tangd`` endpoints are currently hard coded in a ``const`` ``struct`` ([Reference](https://github.com/latchset/tang/blob/master/tangd.c#L142-L146)).

**Comment by mbarnes** [comment]
I don't think Tang has versioned itself.  I would imagine any major revisions would compel a project rename (e.g. Tang2), which we could reflect in the endpoint path (`/tang2/...`).

**Comment by mbarnes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[multi-host-mgr-2] Wrapper Tang API](https://trello.com/c/dtv28IkI/642-multi-host-mgr-2-wrapper-tang-api)

**Comment by ashcrow** [comment]
I mean in terms of our API. We may want to change where we mount things and that would up the API version from ``/vX/`` to ``/vY/``.

**Comment by mbarnes** [comment]
> I mean in terms of our API. We may want to change where we mount things and that would up the API version from /vX/ to /vY/.

Fair enough.

**Comment by mbarnes** [comment]
I'm closing this since it doesn't look like Tang integration is feasible in Commissaire at this time.  Can reopen in the future if that changes.

**Comment by ashcrow** [comment]
@npmccallum let us know if you have any ideas on how we could integrate will!

**Comment by npmccallum** [comment]
I'm having a hard time piecing together what the precise problem is. Is the only problem that you need a JSONRPC API?

**Comment by mbarnes** [comment]
@npmccallum Proxying the REST API was just a supplemental feature.

The real use case was to automate registering a cluster node with a Tang server for automatic disk decryption.

The problem is twofold:
 * An already-encrypted root volume would require manual decryption on first boot before Commissaire could act on it.  A manual step is unacceptable for a cluster node.
 * AFAICT, there exists no safe and reliable way to encrypt a root volume once the OS is installed and the host is up and running.  Especially not remotely over an SSH connection (via Ansible).  So having Commissaire both encrypt the volume and register the host with Tang is also not feasible.

It seemed to me the only way to automate host registration with Tang was at OS installation time, either through a Kickstart file or through Anaconda directly.  But I'm certainly open to other ideas.

**Comment by npmccallum** [comment]
@mbarnes I'm not sure I understand your precise workflow. Generally, you are correct -- you need to encrypt the disk up front and keep the password secret until you bind with Clevis. However, it might be possible to encrypt the data up front and perform online reencryption at a later point. This would let you use a static key in the beginning -- with no security -- but migrate to a cryptographically strong key later through online reencryption. It might even be possible, in the future, to "encrypt" the disk using a null cipher (that is, not encrypted at all) and later do online reencryption to provide a real key.

But I feel you're right. If you don't control the original provisioning, enabling crypto later would be difficult.
